### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by sierraalpha83** [autonomylab-xyz/grass#4]
Hi, it's not running, I used docker compose.

Logs in Docker:

`Downloading extension...

Downloaded! Installing extension and driver manager...

Installed! Starting...

Started! Logging in...

Loading login form...

Traceback (most recent call last):

  File "/usr/src/app/./main.py", line 132, in <module>

    user.send_keys(USER)

  File "/usr/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 231, in send_keys

    self._execute(

  File "/usr/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute

    return self._parent.execute(command, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute

    self.error_handler.check_response(response)

  File "/usr/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response

    raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable

  (Session info: chrome=123.0.6312.58)`

**Comment by lein1013** [comment]
check https://github.com/MRColorR/get-grass - seems to work
